name: Testing Pipeline DevOps

on:
 push:
  branches:
  - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Pipeline Setup
     run: echo "Hello, GitHub Actions! The pipeline is running."
   - name: Stage 1:-Build Application
     run : |
      echo "Building the Application..."
      mkdir build
      echo "Build Successful!"
   - name: Stage 2:-Run Tests
     run : |
      echo "Running Tests..."
      exit 0

