name:Testing Pipeline DevOps
on:
push:
branch:
- main

jobs:
build:
runs-on:ubuntu-latest

steps:
- name:Checkout code
uses:actions/chechout@v4
- name:Pipeline SetUp
run:echo "Hello, GitHub Actions! This pipeline is running."
